const prisma = require("../config/prisma");

/**
 * Service contains logic for:
 * - Chunking (data after cleaning).
 * - Vectorization (using SBERT).
 * - Storing and retrieving vectors from the database.
 */

const { cleaningText } = require("../utils/preprocessing/textCleaner");
const { textChunking } = require("../utils/preprocessing/textChunking");
const { getEmbedding } = require("../utils/preprocessing/textEmbedding");
const {
  textStandardization,
} = require("../utils/preprocessing/textStandardization");

/**
 * @typedef {Object} ProcessedChunk
 * @property {string} content - raw text chunk after cleaning and chunking
 * @property {number[]} embedding - vector representation of the chunk generated by the embedding model
 * @property {number} index - the order of the chunk in the original text (starting from 0)
 */

/**
 * @param {string} id - job ID
 * @param {ProcessedChunk[]} processedChunks - An array of objects containing chunk content, its embedding, and index
 */
async function storeNewJobVector(id, processedChunks) {
  if (!id || !processedChunks || !Array.isArray(processedChunks)) {
    throw new Error("Invalid input for storeJobVector");
  }

  /**
   * Storing each chunk and its embedding in the database. We use a transaction to ensure that all chunks for a job are stored together, maintaining data integrity.
   * Each chunk is associated with the job ID, and we also store the index to keep track of the original order of the chunks. This will be important for reconstructing the text or for any operations that require understanding the sequence of the chunks.
   * The embedding is stored as a JSON string since it is an array of numbers, which allows us to easily retrieve and use it later for similarity searches or other vector-based operations.
   */

  try {
    const transaction = await prisma.$transaction(async (tx) => {
      for (const chunk of processedChunks) {
        await tx.$executeRaw`
          INSERT INTO "JobChunk" (id, "jobId", content, embedding)
          VALUES (${uuidv4()}, ${jobId}, ${chunks[i]}, ${vectorString}::vector)
        `;
      }
      await tx.job.update({
        where: { id: jobId },
        data: { vectorStatus: "COMPLETED" },
      });
    });
  } catch (error) {
    console.error(`Lỗi vector hóa Job ${jobId}:`, error);
    await prisma.job.update({
      where: { id: jobId },
      data: { vectorStatus: "FAILED" },
    });
  }
}

async function updateExistingJobVector(jobId, processedChunks) {
  if (!id || !processedChunks || !Array.isArray(processedChunks)) {
    throw new Error("Invalid input for storeJobVector");
  }

  try {
    const transaction = await prisma.$transaction(async (tx) => {
      // delete existing chunks for the job before updating with new chunks to avoid duplication and maintain data integrity
      await tx.jobChunk.deleteMany({
        where: { jobId },
      });

      // insert new chunks with updated content and embeddings
      for (const chunk of processedChunks) {
        await tx.$executeRaw`
          INSERT INTO "JobChunk" (id, "jobId", content, embedding)
          VALUES (${uuidv4()}, ${jobId}, ${chunk.content}, ${JSON.stringify(chunk.embedding)}::vector)
        `;
      }
      await tx.job.update({
        where: { id: jobId },
        data: { vectorStatus: "COMPLETED" },
      });
    });
  } catch (error) {
    console.error(`Lỗi cập nhật vector hóa Job ${jobId}:`, error);
    await prisma.job.update({
      where: { id: jobId },
      data: { vectorStatus: "FAILED" },
    });
  }
}

async function processAndStoreJobVector(job) {
  // Step 1: Clean the job data to remove noise and irrelevant information
  const cleanedText = cleaningText(job);
  if (!cleanedText) {
    console.warn(
      `Job ${job.id} has insufficient content after cleaning. Skipping vectorization.`,
    );
    return;
  }
  // Step 2: Standardize the cleaned text to ensure consistent representation, especially for Vietnamese text
  const standardizedText = textStandardization(cleanedText);
  // Step 3: Chunk the standardized text into smaller pieces suitable for embedding generation
  let chunks = [];
  chunks = textChunking(standardizedText);
  if (chunks.length === 0) {
    console.warn(
      `Job ${job.id} has no valid chunks after chunking. Skipping vectorization.`,
    );
  }
  // Step 4: Generate embeddings for each chunk using the embedding model
  let chunkEmbeddings = [];
  chunkEmbeddings = await Promise.all(
    chunks.map(async (chunk) => {
      const embedding = await getEmbedding(chunk);
      return embedding;
    }),
  );
  // Step 5: Create processed chunks with embeddings
  // Check if job id is exists in the database before storing
  // if it exists, we can update the existing chunks and embeddings instead of creating new ones to avoid duplication and maintain data integrity

  const existingChunks = await prisma.jobChunk.findMany({
    where: { jobId: job.id },
  });

  const processedChunks = chunks.map((chunk, index) => ({
    content: chunk,
    embedding: chunkEmbeddings[index],
    index,
  }));
  if (!existingChunks || existingChunks.length === 0) {
    // Step 6: Store the processed chunks and their embeddings in the database
    await storeNewJobVector(job.id, processedChunks);
  } else {
    await updateExistingJobVector(job.id, processedChunks);
  }
}

module.exports = {
  storeJobVector,
  processAndStoreJobVector,
};
