const STOP_WORDS = [
  "và",
  "không",
  "có",
  "với",
  "cho",
  "của",
  "là",
  "các",
  "những",
  "một",
  "trong",
  "ngoài",
  "trên",
  "dưới",
  "đã",
  "đang",
  "sẽ",
  "cũng",
  "đều",
  "từ",
  "đến",
  "tại",
  "vào",
  "ra",
  "lên",
  "xuống",
  "thì",
  "mà",
  "nhưng",
  "hoặc",
  "nếu",
  "như",
  "vậy",
  "thế",
  "còn",
  "vì",
  "nên",
  "bởi",
  "do",
  "tại",
  "vừa",
  "mới",
  "hay",
  "cần",
  "muốn",
  "phải",
  "biết",
  "làm",
  "được",
  "bị",
  "cho",
  "để",
  "này",
  "kia",
  "đó",
  "nào",
  "gì",
  "ai",
  "đâu",
  "khi",
  "lúc",
  "vừa",
  "rất",
  "quá",
  "lắm",
  "hơn",
  "nhất",
  "luôn",
  "thường",
  "hay",
  "ít",
  "nhiều",
  "a",
  "an",
  "the",
  "and",
  "or",
  "but",
  "if",
  "then",
  "else",
  "when",
  "at",
  "from",
  "by",
  "for",
  "with",
  "about",
  "against",
  "between",
  "into",
  "through",
  "during",
  "before",
  "after",
  "above",
  "below",
  "to",
  "from",
  "up",
  "down",
  "in",
  "out",
  "on",
  "off",
  "over",
  "under",
  "again",
  "further",
  "then",
  "once",
  "here",
  "there",
  "all",
  "any",
  "both",
  "each",
  "few",
  "more",
  "most",
  "other",
  "some",
  "such",
  "no",
  "nor",
  "not",
  "only",
  "own",
  "same",
  "so",
  "than",
  "too",
  "very",
  "s",
  "t",
  "can",
  "will",
  "just",
  "don",
  "should",
  "now",
  "i",
  "me",
  "my",
  "myself",
  "we",
  "our",
  "ours",
  "ourselves",
  "you",
  "your",
  "yours",
  "yourself",
  "yourselves",
  "he",
  "him",
  "his",
  "himself",
  "she",
  "her",
  "hers",
  "herself",
  "it",
  "its",
  "itself",
  "they",
  "them",
  "their",
  "theirs",
  "themselves",
  "what",
  "which",
  "who",
  "whom",
  "this",
  "that",
  "these",
  "those",
  "am",
  "is",
  "are",
  "was",
  "were",
  "be",
  "been",
  "being",
  "have",
  "has",
  "had",
  "having",
  "do",
  "does",
  "did",
  "doing",
  // Add more stop words as needed
];

const ABBREVIATIONS = {
  tv: "thành viên",
  ko: "không",
  dc: "được",
  đc: "được",
  đk: "đăng ký",
  cs: "có",
  đt: "đào tạo",
  kn: "kinh nghiệm",
  nv: "nhân viên",
  cty: "công ty",
  tuyển: "tuyển dụng",
  offer: "đề nghị",
  nlđ: "người lao động",
  hc: "hành chính",
  bh: "bảo hiểm",
  bhxh: "bảo hiểm xã hội",
  bhyt: "bảo hiểm y tế",
  sr: "senior",
  jr: "junior",
  exp: "experience",
  edu: "education",
  tech: "technology",
  dev: "developer",
  sys: "system",
  mgmt: "management",
  qa: "quality assurance",
  qc: "quality control",
  hr: "human resources",
  dept: "department",
  info: "information",
  approx: "approximately",
  etc: "et cetera",
  vs: "versus",
};

const TECH_MAPPING = {
  // Frontend & Frameworks (Tiếp nối của Hào)
  "node.js": "nodejs",
  "node js": "nodejs",
  "react.js": "reactjs",
  "react js": "reactjs",
  "angular.js": "angularjs",
  "angular js": "angularjs",
  "vue.js": "vuejs",
  "vue js": "vuejs",
  "next.js": "nextjs",
  "next js": "nextjs",
  "express.js": "expressjs",
  "express js": "expressjs",
  "nuxt.js": "nuxtjs",
  "nuxt js": "nuxtjs",
  "svelte.js": "sveltejs",
  "svelte js": "sveltejs",

  // Languages with Special Characters (Rất quan trọng để tránh lỗi Token)
  "c#": "csharp",
  "c #": "csharp",
  "c++": "cpp",
  "c ++": "cpp",
  "f#": "fsharp",
  "objective-c": "objectivec",
  "dot net": "dotnet",
  ".net": "dotnet",
  "asp.net": "aspnet",
  "core .net": "dotnetcore",

  // Mobile & Cross-platform
  "react native": "reactnative",
  flutter: "flutter",
  kotlin: "kotlin",
  swift: "swift",
  dart: "dart",

  // Databases & Storage (Để lọc Job theo Stack dữ liệu)
  mongodb: "mongodb",
  "mongo db": "mongodb",
  postgresql: "postgresql",
  postgres: "postgresql",
  mysql: "mysql",
  "sql server": "sqlserver",
  mssql: "sqlserver",
  redis: "redis",
  elasticsearch: "elasticsearch",

  // DevOps, Cloud & Tools
  aws: "amazonwebservices",
  "amazon web services": "amazonwebservices",
  "google cloud": "gcp",
  azure: "azure",
  docker: "docker",
  kubernetes: "k8s",
  jenkins: "jenkins",
  "github actions": "githubactions",
  "ci/cd": "cicd",
  cicd: "cicd",

  // Big Data & AI
  "machine learning": "machinelearning",
  "deep learning": "deeplearning",
  "artificial intelligence": "ai",
  "big data": "bigdata",
  "data science": "datascience",
};
module.exports = { STOP_WORDS, ABBREVIATIONS, TECH_MAPPING };
