-- CreateEnum
CREATE TYPE "VECTOR_STATUS" AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED');

-- AlterTable
ALTER TABLE "jobs" ADD COLUMN     "vector_status" "VECTOR_STATUS" NOT NULL DEFAULT 'PENDING';
